### ISSUE TITLE
Richer Persian Lexicon

### ISSUE THREAD

**Issue by samanvp** [Qiamast/PersianWordle#1]
Hi,
I just created [this repo](https://github.com/samanvp/persian-lexicon) and I though it might be helpful to your project.

**Comment by Qiamast** [comment]
Hi, Saman Thank you for the issue :) @PersianWordle now has more than 12k 5 letter words on a whitelist, and +500 selected words for the main section.  Your repo looks good plz first clone Persian wordle and add your repo in `/python` dir and send PR to this Project.

**Comment by samanvp** [comment]
Thanks for your reply.
I was originally working on a [wordle solver](https://github.com/samanvp/wordle-solver) and because I was not able to find a clean list of Persian words I decided to create and publish those lexicons. I though your project might also benefit from them.

Please note that those lexicons are not manually curated. Probably someone should go over them and drop irrelevant/offensive words.

Good luck and thanks for PersianWordle!
